name: GitHub Page Deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure NodeJS v10
      uses: actions/setup-node@v2
      with:
        node-version: 10
        cache: 'npm'
  
    - name: Install Project Dependencies via NPM
      run: npm ci

    - name: Typecheck Available JS Code
      run: npm run typecheck

    - name: Execute Jest JS Test Runner
      run: npm run test -- --watchAll=false

    - name: Build Production React Bundle
      run: npm run build

    - name: Deploy to GitHub Pages
      if: ${{ github.event_name == 'push' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.GH_PAGE_DEPLOY_ACTION_PRIVATE_KEY }}
        external_repository: garrett-s-wininger/garrett-s-wininger.github.io
        publish_branch: main
        publish_dir: ./build
