name: Build, Test, and Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  main:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Configure NodeJS v10
      uses: actions/setup-node@v2
      with:
        node-version: 10
        cache: 'npm'
    - name: Install Project Dependencies via NPM
      run: npm ci
    - name: Typecheck Available JS Code
      run: npm run typecheck
    - name: Execute Jest JS Test Runner
      run: npm test -- --watchAll=false
